Fixed the possibility to compile using a version of GCC older than 8.0
BlitterStudio/amiberry pull request #1007
Opened 2022-08-23 20:10 UTC by farox1

Fixes # . Fixed the possibility to compile using a version of GCC older than 8.0 where filesystem is found under <experimental/filesystem>
          Tested only on my Linux Box AMD E1, Mint 19.3 , GCC 7.5

Changes proposed in this pull request:
- Makefile added option USE_OLDGCC
- main.cpp and amiberry_filesys.cpp fixed include and some lines where filesystem where used
-
-

@midwan

2022-08-23 20:38 UTC, farox1 commented
Sorry for the changes on Template file....this doesn't had to be modified...but this is one of the first Pull-request for me.

2022-08-24 07:35 UTC, midwan requested changes
Looks good, thanks.
If you could just revert the change to the template, we can merge this in.

2022-08-24 07:35 UTC, midwan commented on PULL_REQUEST_TEMPLATE
> +-
I guess you can revert this change, since it was done by mistake?

2022-08-24 11:22 UTC, farox1 commented
Sorry i'm at work....i don't know how to revert the changes on template file...maybe i need to redo the pull-request from start?
 I could take a look at it in the evening.

2022-08-24 18:55 UTC, closed without merging